# %%%%%%%%%%%%%%%%%%%%%%
# %%% PLOT STRUCTURE %%%
# %%%%%%%%%%%%%%%%%%%%%%

# This script declares 2 functions: one for plotting a single STRUCTURE plot, and one for plotting all
# of the STRUCTURE output files in a specified folder. It then demonstrates each function using the 
# STRUCTURE output files within the HybridSimulation repository.

# Set working directory to relevant repository
gitHub.wd <- "/home/chendrikse/Shared/HybridSimulation/"
setwd(gitHub.wd)

library(RColorBrewer)
library(pophelper)

# Declare path variables, for demonstrating plotting functions below
# Single STRUCTURE file
testStructFile <- paste0(gitHub.wd,"Scenarios/4sp_10ms_20ns/StructOut1/parentandhybrid4Deme_1_f")
# Folder of STRUCTURE files
testStructFolder <- paste0(gitHub.wd,"Scenarios/4sp_10ms_20ns/StructOut1/")
# Colors to use for plotting (RGB components in hexadecimal)
test.colors <- c('#A8FFFD','#B862D3', '#A39D9D','#FFFF00','#69C261', '#FF59AC', '#26CDCD',  '#C1C6FF')

# Function for reading in a single STRUCTURE file, and plotting it
plotSTRUCTURE_single <- function(structFile, colors, title){
  # Read in the STRUCTURE file, using the readQStructure function
  Qmat <- readQStructure(files = structFile)
  # Capture the name of the Q matrix, and combine it with the title argument. This will be used as the plot title
  structName <- paste0(title, ": ", names(Qmat))
  # Convert the list object generated by readQStructure to a data.frame, for plotting purposes
  Qmat <- as.data.frame(unlist(Qmat, recursive = FALSE))
  # Plotting: loop through the columns of the Q matrix (where each column is a K value), plotting column by column
  for(i in 1:length(Qmat)){
    if(i==1){
      # Initial barplot, for first column of values
      barplot(Qmat[,i], xlim=c(0,(nrow(Qmat)+20)), ylim=c(0,1.3), horiz=F, beside=F, 
              col=colors[i], axisnames=T, space=0.2, yaxt= "n", main=structName)
      off.value <- Qmat[,i]
    }else{
      # Subsequent barplots, with offset (to stack columns, as necessary)
      barplot(Qmat[,i], offset=off.value, add=T, beside=F, xlim=c(0,(nrow(Qmat)+20)), 
              horiz=F, col=colors[i], yaxt= "n")
      off.value <- off.value + Qmat[,i]
    }
  }
  # Add in a y axis, which shows genomic proportions
  axis(2, at = c(0, 0.25, 0.5, 0.75, 1), labels=c("0", "0.25", "0.50", "0.75", "1.00"), cex.axis = 1, las = 2, pos = -0.2, xpd=T)
}

# Plot single file
plotSTRUCTURE_single(structFile = testStructFile, colors = test.colors, title = "4sp_10ms_20ns")

# Function for reading in each STRUCTURE file in a folder, and plotting it 
plotSTRUCTURE_multiple <- function(folder, plotColors, scenarioNames){
  # Capture current working directory, to return to when the function completes
  original.wd <- getwd()
  # Navigate to the folder containing STRUCTURE output files to be plotted
  setwd(folder)
  # Make a list of STRUCTURE output files within the specified folder. Currently, this will read in ALL files in the folder
  structFiles <- dir()
  # Set graphing parameters to allow for multiple rows (one for each STRUCTURE file)
  par(mfrow = c(length(structFiles),1), mar = c(2.5,1,2,0.75) + 0.1, oma = c(1.5,0,3,0), mgp = c(2,1,0))
  # Apply the plotSTRUCTURE_single function to each item within the list (using lapply)
  lapply(structFiles, plotSTRUCTURE_single, colors=plotColors, title=scenarioNames)
  # Return to original working directory
  setwd(original.wd)
}

# Demonstration
plotSTRUCTURE_multiple(folder = testStructFolder, plotColors = test.colors, scenarioName = "4sp_10ms_20ns")
